// 用户所有的权限列表
export default [
   {
     name:'首页',
     icon:'home',
     path:'/admin/home',
     id:'0'
   },
   {
     name:'用户管理',
     icon:'user',
     id:'1',
     path:'/admin/user'
   },
   {
     name:'商品管理',
     icon:"",
     path:'',
     id:'2',
     children:[
       {
         name:'商品列表',
         path:'/admin/goods/list',
         id:'2-0'
       },
       {
         name:'商品添加',
         path:'/admin/goods/add',
         id:'2-1'
       }
     ]
   },
   {
    name:'数据统计',
    icon:'',
    path:'',
    id:'3',
    children:[
      {
        name:'数据报表',
        path:'/admin/data/dataing',
        id:'3-0'
      }
    ]
  }
 ]